spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://${SQL_HOST}:3306/${SQL_DB}?serverTimezone=UTC
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update