spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  jpa:
    propoerties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
