spring:
  config:
    import:
      - optional:classpath:/application-local.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true

    # 정적 리소스에 변화가 있을 때 바로 반영한다.
    devtools:
      livereload:
        enabled: true

    # thymeleaf 참조 경로
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      check-template-location: true

auth.jwt:
  issuer: ${JWT_ISSUER}
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}
  expiration: 60 # minutes
  refreshExpiration: 100 # days

# OAuth Security
oauth2:
  provider:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: http://localhost:8080/login/oauth2/code/google
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: http://localhost:8080/login/oauth2/code/naver
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
    github:
      client-id: ${GIT_CLIENT_ID}
      client-secret: ${GIT_CLIENT_SECRET}
      redirect-uri: http://localhost:8080/login/oauth2/code/github
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user